---
author: Cybersecurity and Infrastructure Security Agency
branding:
  color: blue
  icon: shield
description: >-
  Our standard permissions monitoring and runner hardening that is to
  be applied at the beginning of each GitHub Actions job.
name: Job preamble

inputs:
  actions_permissions_config:
    description: >-
      The permission configuration to use.  You will usually want to
      set this to `${{ vars.ACTIONS_PERMISSIONS_CONFIG }}`.
    required: true

runs:
  using: composite
  steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ inputs.actions_permissions_config }}
    - id: harden-runner
      name: Harden the runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit
