---
author: Cybersecurity and Infrastructure Security Agency

branding:
  color: blue
  icon: shield

description: >-
  Our standard permissions monitoring and runner hardening that is to
  be applied at the beginning of each GitHub Actions job.

name: Job preamble

inputs:
  check_github_status:
    default: "false"
    description: >-
      A Boolean ("true"/"false") value indicating whether or not to
      check GitHub status using the crazy-max/ghaction-github-status
      GitHub action.
    required: false

  harden_runner:
    default: "true"
    description: >-
      A Boolean ("true"/"false") value indicating whether or not to
      harden the runner using the step-security/harden-runner GitHub
      action.
    required: false

  harden_runner_egress_policy:
    default: audit
    description: >-
      The egress policy to use for runner hardening.  Valid values are
      audit and block.  See step-security/harden-runner for more
      details.
    required: false

  monitor_permissions:
    default: "true"
    description: >-
      A Boolean ("true"/"false") value indicating whether or not to
      monitor GitHub permission requests using the
      GitHubSecurityLab/actions-permission/monitor GitHub action.
    required: false

  output_workflow_context:
    default: "false"
    description: >-
      A Boolean ("true"/"false") value indicating whether or not to
      output the workflow context using the
      crazy-max/ghaction-dump-context GitHub action.
    required: false

  permissions_monitoring_config:
    default: ""
    description: >-
      A JSON string containing the configuration to use for
      permissions monitoring.  In the case of cisagov you will almost
      usually to set this to `\$\{\{ vars.ACTIONS_PERMISSIONS_CONFIG
      \}\}` so it agrees with our organization-wide GitHub Actions
      permissions monitoring configuration.  See the documentation for
      the GitHubSecurityLab/actions-permission/monitor action for more
      details:
      https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor#configuration
    required: false

# We use a shell argument for each step that provides the same guardrails we
# would have in our bash scripts. The `-Eueo pipefail` sets errtrace, nounset,
# errexit, and pipefail. The `-x` will print all commands as they are run. We
# are currently unable to set this as a default (like we can in workflows) so
# this must be added to each step that runs shell commands. Please see the
# following GitHub discussion that requests this feature for any status
# updates: https://github.com/orgs/community/discussions/18597

runs:
  using: composite
  steps:
    - id: monitor-actions-permissions
      if: ${{ inputs.monitor_permissions == 'true' }}
      name: Monitor GitHub Actions permissions
      uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ inputs.permissions_monitoring_config }}

    - id: harden-runner
      if: ${{ inputs.harden_runner == 'true' }}
      name: Harden the runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: ${{ inputs.harden_runner_egress_policy }}

    - id: check-github-status
      if: ${{ inputs.check_github_status == 'true' }}
      name: Check GitHub status
      uses: crazy-max/ghaction-github-status@v5

    - id: output-workflow-context
      if: ${{ inputs.output_workflow_context == 'true' }}
      name: Output workflow context
      uses: crazy-max/ghaction-dump-context@v2
