---
author: Cybersecurity and Infrastructure Security Agency
branding:
  color: blue
  icon: shield
description: >-
  Our standard permissions monitoring and runner hardening that is to
  be applied at the beginning of each GitHub Actions job.
name: Job preamble

inputs:
  actions_permissions_config:
    description: >-
      A JSON string containing the permissions configuration to use
      for permissions monitoring.  In the case of cisagov you will
      usually want to set this to `\$\{\{
      vars.ACTIONS_PERMISSIONS_CONFIG \}\}` so it agrees with our
      organization-wide GitHub Actions permissions configuration.  See
      the documentation for the
      GitHubSecurityLab/actions-permission/monitor action for more
      details:
      https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor#configuration
    required: true

runs:
  using: composite
  steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ inputs.actions_permissions_config }}
    - id: harden-runner
      name: Harden the runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit
